# -*- coding: utf-8 -*-
"""k-means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a7dfz-l6Er6B_PSiHKSnp7u8y0u6TER3

# IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# import dataset"""

data = pd.read_csv('Iris.csv')

X = data.iloc[:,1:5]

"""# NORMALIZE THE DATASET FOR PCA"""

from sklearn.preprocessing import StandardScaler
Sc_x=StandardScaler()
X=Sc_x.fit_transform(X)

"""# USE PCA TO REDUCE THE DIMENSIONS"""

from sklearn.decomposition import PCA

pca = PCA(n_components=2)

X = pca.fit_transform(X)

explained = pca.explained_variance_ratio_

explained

"""# Use ELBOW METHOD"""

from sklearn.cluster import KMeans
wcss = []
for i in range(1,11) :
  kmeans = KMeans(n_clusters=i,init='k-means++',max_iter=300,n_init=10,random_state=0)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)
plt.plot(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('wcss')

"""# Once number of Clusters Decide fit to X"""

kmeans = KMeans(n_clusters=3,init='k-means++',max_iter=300,n_init=10,random_state=0)
y_kmeans = kmeans.fit_predict(X)

"""# WE GOT OUR CATEGORIES OR LABEL(Y)"""

y_kmeans

"""# VISUALIZE"""

plt.scatter(X[y_kmeans == 0,0],X[y_kmeans == 0,1] , s=100 , c='red' ,label = 'cluster 1')
plt.scatter(X[y_kmeans == 1,0],X[y_kmeans == 1,1] , s=100 , c='blue' ,label = 'cluster 2')
plt.scatter(X[y_kmeans == 2,0],X[y_kmeans == 2,1] , s=100 , c='green' ,label = 'cluster 3')
plt.scatter(kmeans.cluster_centers_[:,0] , kmeans.cluster_centers_[:,1] , s=300 , c='yellow' ,label = 'centriods')
plt.title('Clusters')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.legend()
plt.show()